/**
 * Created by Administrator on 2017/6/21.
 */

/***** 01-09 (WXN)  *****/
/***** 10-18 (ZhYN) *****/
/***** 19-27 (ZhQK) *****/
/***** 28-36 (WJ)   *****/
/***** 37-45 (TJX)  *****/
/***** 46-54 (TJL)  *****/

var data=[
    {
        id:1,
        name:'钻石雪域牛乳芝士蛋糕',
		enName:'Diamond Cheesecake',
        price:'218.00',
        isRecommend:false,
        isNews:true,
        isBlast:false,
        isHot:false,
        isSign:false,
        isSale:false,
        isPrompt:false,
        isLimit:false,
        isStand:false,
        images:['id1.jpg','id1_b.jpg'],
        norms:[{offer:'2-4',price:'218.00',content:'13*13',cutlery:'5',sweet:true,weight:'480'},
            {offer:'5-8',price:'336.00',content:'17*17',cutlery:'10',sweet:true,weight:'620'},
            {offer:'10-12',price:'504.00',content:'22*22',cutlery:'15',sweet:true,weight:'1050'},
            {offer:'15-20',price:'840.00',content:'31*31',cutlery:'20',sweet:true,weight:'1750'}],
        detImages:['id1_1.jpg','id1_2.jpg'],
        aboutFood:[{a1:'奶油芝士',b1:'Cream Cheese',c1:'澳大利亚',
            a2:'无盐黄油',b2:'Butter',c2:'新西兰',
            a3:'起泡葡萄酒',b3:'Sparkling Wine',c3:'美国'}],
        aboutEat:'芝士口味'
    },
    {
        id:2,
        name:'美刀刀蛋糕',
		enName:'Ms. Golden',
        price:'298.00',
        isRecommend:false,
        isNews:false,
        isBlast:true,
        isHot:false,
        isSign:false,
        isSale:false,
        isPrompt:false,
        isLimit:false,
        isStand:false,
        images:['id2.jpg'],
        norms:[{offer:'5-8',price:'298.00',content:'20*16',cutlery:'10',sweet:true,weight:'700'},
            {offer:'12-16',price:'458.00',content:'32*20',cutlery:'20',sweet:true,weight:'1400'}],
        detImages:['id2_1.jpg','id2_2.jpg'],
        p:'芝士与香草戚风被雪域奶油的浪漫笼罩，每一口都充满快乐的滋味，撩拨起无限的食欲，让味蕾懂得了心跳的感觉。',
        aboutFood:[{a1:'奶油芝士',b1:'DAIRY GOOD',c1:'澳大利亚',
            a2:'稀奶油',b2:'纽麦福',c2:'新西兰',
            a3:'嘉利宝白巧克力',b3:'CALLEBAUT',c3:'比利时'}],
        aboutEat:'芝士口味'
    },
    {
        id:3,
        name:'蟹蟹你偷吃',
		enName:'Yum Yum Cake',
        price:'258.00',
        isRecommend:false,
        isNews:false,
        isBlast:false,
        isHot:false,
        isSign:true,
        isSale:true,
        isPrompt:true,
        isLimit:false,
        isStand:false,
        images:['id3.jpg'],
        norms:[{offer:'2-4',price:'258.00',content:'13*13',cutlery:'5',sweet:true,weight:'480'},
            {offer:'5-8',price:'398.00',content:'17*17',cutlery:'10',sweet:true,weight:'850'},
            {offer:'10-12',price:'598.00',content:'22*22',cutlery:'15',sweet:true,weight:'1280'},
            {offer:'15-20',price:'998.00',content:'31*31',cutlery:'20',sweet:true,weight:'2500'}],
        detImages:['id3_1.jpg','id3_2.jpg'],
        aboutFood:[{a1:'芒果果茸',b1:'capfruit',c1:'法国'}],
        aboutEat:'芝士口味'
    },
    {
        id:4,
        name:'雪域牛乳芝士蛋糕',
		enName:'Le Cheesecake',
        price:'198.00',
        isRecommend:false,
        isNews:false,
        isBlast:true,
        isHot:false,
        isSign:false,
        isSale:false,
        isPrompt:false,
        isLimit:false,
        isStand:false,
        images:['id4.jpg','id4_b.jpg'],
        norms:[{offer:'2-4',price:'198.00',content:'13*13',cutlery:'5',sweet:true,weight:'450'},
            {offer:'5-8',price:'298.00',content:'17*17',cutlery:'10',sweet:true,weight:'820'},
            {offer:'10-12',price:'458.00',content:'22*22',cutlery:'15',sweet:true,weight:'1300'},
            {offer:'15-20',price:'756.00',content:'31*31',cutlery:'20',sweet:true,weight:'2600'}],
        detImages:['id4_1.jpg','id4_2.jpg'],
        p:'到过阿尔卑斯山脉勃朗峰才发现，白，其实就这么纯粹。雪花忽聚忽散，轻盈降落在地上，化为一片白。那个清晨，我踏上厚厚的初雪，出乎意料，是松软的触感。',
        aboutFood:[{a1:'白巧克力',b1:'嘉利宝/贝可拉',c1:'比利时',
            a2:'无盐黄油',b2:'Anchor',c2:'新西兰',
            a3:'芝士',b3:'MG/安佳',c3:'新西兰',
            a4:'淡奶油',b4:'铁塔/安佳',c4:'新西兰',
            a5:'全脂牛奶',b5:'得乐思/爱氏晨曦',c5:'法国/德国'}],
        aboutEat:'芝士口味'
    },
    {
        id:5,
        name:'花冠蛋糕',
		enName:'Stephanie Cake',
        price:'298.00',
        isRecommend:false,
        isNews:false,
        isBlast:false,
        isHot:false,
        isSign:false,
        isSale:false,
        isPrompt:false,
        isLimit:false,
        isStand:false,
        images:['id5.jpg'],
        norms:[{offer:'2-4',price:'298.00',content:'18*18',cutlery:'5',sweet:true,weight:'620'},
            {offer:'5-8',price:'458.00',content:'21*21',cutlery:'10',sweet:true,weight:'980'}],
        detImages:['id5_1.jpg','id5_2.jpg'],
        p:'鲜花，裙袂，和煦阳光，塞纳河畔的温柔萦绕着对一个人的思念。丝绒般温暖的淡粉色花冠，正如至爱的抚摸，令每一刻时光都充满馨香甜美。',
        aboutFood:[{a1:'白巧克力',b1:'嘉利宝',c1:'比利时'}],
        aboutEat:'慕斯口味'
    },
    {
        id:6,
        name:'芒果熔岩星球蛋糕',
		enName:'Mango Planet',
        price:'318.00',
        isRecommend:false,
        isNews:true,
        isBlast:false,
        isHot:false,
        isSign:false,
        isSale:true,
        isPrompt:true,
        isLimit:false,
        isStand:true,
        images:['id6.jpg'],
        norms:[{offer:'4-6',price:'318.00',content:'14*14',cutlery:'10',sweet:true,weight:'680'}],
        detImages:['id6_1.jpg','id6_2.jpg'],
        p:'热带季风青睐的阳光地带;到处都是嫩滑丰盈的新鲜芒果;鲜甜的清香撩拨着舌尖;芒果流心的香浓喷薄欲出;甜蜜源泉将实现每个甜蜜愿望。',
        aboutFood:[{a1:'阿方索芒果浓浆',b1:'ShoEi',c1:'印度',
            a2:'稀奶油',b2:'纽麦福',c2:'新西兰',
            a3:'芒果',b3:'精选',c3:'全球'}],
        aboutEat:'鲜果口味'
    },
    {
        id:7,
        name:'提拉米苏乐脆蛋糕',
		enName:'Tiramisu Crispy',
        price:'198.00',
        isRecommend:false,
        isNews:false,
        isBlast:true,
        isHot:false,
        isSign:false,
        isSale:false,
        isPrompt:false,
        isLimit:false,
        isStand:false,
        images:['id7.jpg','id7_b.jpg'],
        norms:[{offer:'2-4',price:'198.00',content:'13*13',cutlery:'5',sweet:true,weight:'430'},
            {offer:'5-8',price:'298.00',content:'17*17',cutlery:'10',sweet:true,weight:'750'},
            {offer:'10-12',price:'458.00',content:'22*22',cutlery:'15',sweet:true,weight:'1150'},
            {offer:'15-20',price:'756.00',content:'31*31',cutlery:'20',sweet:true,weight:'2250'}],
        detImages:['id7_1.jpg','id7_2.jpg'],
        p:'带我走。是Tiramisu意大利文的意思。意大利甜品师用它带走了法国女孩的心，还在巴黎开了一间小店，分享这幸福的味道。他，令人芳心暗许。',
        aboutFood:[{a1:'芝士',b1:'琪雷萨',c1:'意大利/美国',
            a2:'牛奶巧克力',b2:'嘉利宝/贝可拉',c2:'比利时',
            a3:'可可薄脆',b3:'可可百利',c3:'法国',
            a4:'幼砂糖',b4:'雪花',c4:'韩国',
            a5:'榛果酱',b5:'嘉利宝/贝可拉',c5:'比利时',
            a6:'淡奶油',b6:'铁塔/安佳',c6:'进口'}],
        aboutEat:'芝士口味'
    },
    {
        id:8,
        name:'哈!蜜瓜蛋糕',
		enName:'Hey Melon',
        price:'318.00',
        isRecommend:false,
        isNews:true,
        isBlast:false,
        isHot:false,
        isSign:false,
        isSale:true,
        isPrompt:true,
        isLimit:false,
        isStand:true,
        images:['id8.jpg'],
        norms:[{offer:'4-6',price:'318.00',content:'12*12',cutlery:'10',sweet:true,weight:'500'}],
        detImages:['id8_1.jpg','id8_2.jpg'],
        p:'哈密瓜的梦乡里;传递着夏天的气息;淡淡的 柔柔的;海绵蛋糕、果肉夹心、蜜瓜味啫喱……;夹心丰富 层层惊喜;一个蜜瓜吃出无穷回味。',
        aboutFood:[{a1:'黑巧克力',b1:'callebaut',c1:'比利时',
            a2:'蜜瓜味力娇酒',b2:'bols',c2:'荷兰',
            a3:'稀奶油',b3:'纽麦福',c3:'新西兰',
            a4:'无盐黄油',b4:'anchor',c4:'新西兰',
            a5:'白巧克力',b5:'callebaut',c5:'比利时'}],
        aboutEat:'慕斯口味、慕斯口味、奶油口味'
    },
    {
        id:9,
        name:'钻石大理石雪域双拼蛋糕',
		enName:'Diamond & Marble Cheesecake',
        price:'198.00',
        isRecommend:false,
        isNews:false,
        isBlast:false,
        isHot:false,
        isSign:false,
        isSale:false,
        isPrompt:false,
        isLimit:true,
        isStand:false,
        images:['id9.jpg'],
        norms:[{offer:'2-4',price:'198.00',content:'13*13',cutlery:'5',sweet:true,weight:'500'},
            {offer:'5-8',price:'298.00',content:'17*17',cutlery:'10',sweet:true,weight:'900'},
            {offer:'10-12',price:'458.00',content:'22*22',cutlery:'15',sweet:true,weight:'1550'},
            {offer:'15-20',price:'756.00',content:'31*31',cutlery:'20',sweet:true,weight:'3000'}],
        detImages:['id9_1.jpg','id9_2.jpg'],
        aboutFood:[{a1:'奶油芝士',b1:'Cream Cheese',c1:'澳大利亚',
            a2:'无盐黄油',b2:'Butter',c2:'新西兰',
            a3:'起泡葡萄酒',b3:'Sparkling Wine',c3:'美国',
            a4:'巧克力',b4:'Callebaut',c4:'比利时'}],
        aboutEat:'芝士口味'
    },
    {
        id:10,
        name:'芒果大理石雪域双拼蛋糕',
		enName:'Mango & Marble Cheesecake',
        price:'198.00',
        isRecommend:'false',
        isNews:false,
        isBlast:false,
        isHot:false,
        isSign:false,
        isSale:false,
        isPrompt:true,
        isLimit:false ,
        isStand:false ,
        images:['10.jpg'],
        norms:[{offer:'2-4',price:'198',content:'13*13',cutlery:'5',sweet:true,weight:'420g'},
            {offer:'5-8',price:'298',content:'17*17',cutlery:'10',sweet:true,weight:'750g'},
            {offer:'10-12',price:'458',content:'22*22',cutlery:'15',sweet:true,weight:'1300g'},
            {offer:'15-20',price:'756',content:'31*31',cutlery:'10',sweet:true,weight:'2500g'}],
        detImages:['10_1.jpg','10_2.jpg'],
        aboutFood:[{a1:'黄油',b1:'安佳/铁塔',c1:'进口',
            a2:'全脂牛奶',b2:'爱氏晨曦',c2:'进口'}],
        aboutEat:'芝士口味'
    },
    {
        id:11,
        name:'芒果钻石雪域双拼蛋糕',
		enName:'Mango & Marble Cheesecake',
        price:'198.00',
        isRecommend:false,
        isNews:false,
        isBlast:false,
        isHot:false,
        isSign:false,
        isSale:false,
        isPrompt:true,
        isLimit:false,
        isStand:false,
        images:['11.jpg'],
        norms:[{offer:'2-4',price:'198',content:'13*13',cutlery:'5',sweet:true,weight:'550'},
            {offer:'5-8',price:'298',content:'17*17',cutlery:'10',sweet:true,weight:'950'},
            {offer:'10-12',price:'458',content:'22*22',cutlery:'15',sweet:true,weight:'1300'},
            {offer:'15-20',price:'756',content:'31*31',cutlery:'10',sweet:true,weight:'2500'}],
        detImages:['11_1.jpg','11_2.jpg'],
        aboutFood:[{a1:'奶油芝士',b1:'Cream Cheese',c1:'澳大利亚',
            a2:'无盐黄油',b2:'Butter',c2:'新西兰'}],
        aboutEat:'芝士口味'
    },
    {
        id:12,
        name:'蓝莓钻石雪域双拼蛋糕',
		enName:'Blueberry & Marble Cheesecake',
        price:'198.00',
        isRecommend:false,
        isNews:false,
        isBlast:false,
        isHot:false,
        isSign:false,
        isSale:false,
        isPrompt:true,
        isLimit:false ,
        isStand:false,
        images:['12.jpg'] ,
        norms:[{offer:'2-4',price:'198',content:'13*13',cutlery:'5',sweet:true,weight:'550'},
            {offer:'5-8',price:'298',content:'17*17',cutlery:'10',sweet:true,weight:'950'},
            {offer:'10-12',price:'458',content:'22*22',cutlery:'15',sweet:true,weight:'1580'},
            {offer:'15-20',price:'756',content:'31*31',cutlery:'10',sweet:true,weight:'3100'}],
        detImages:['12_1.jpg','12_2.jpg'],
        aboutFood:[{a1:'奶油芝士',b1:'Cream Cheese',c1:'澳大利亚',a2:'无盐黄油',b2:'Butter',c2:'新西兰'}],
        aboutEat:'芝士口味'
    },
    {
        id:13,
        name:'蓝莓芒果钻石雪域双拼蛋糕',
		enName:'Blueberry & Marble Cheesecake',
        price:'198.00',
        isRecommend:false,
        isNews:false,
        isBlast:false,
        isHot:false,
        isSign:false,
        isSale:false,
        isPrompt:true,
        isLimit:false ,
        isStand:false,
        images:['13.jpg'],
        norms:[{offer:'2-4',price:'198',content:'13*13',cutlery:'5',sweet:true,weight:'450'},
            {offer:'5-8',price:'298',content:'17*17',cutlery:'10',sweet:true,weight:'800'},
            {offer:'10-12',price:'458',content:'22*22',cutlery:'15',sweet:true,weight:'1300'},
            {offer:'15-20',price:'756',content:'31*31',cutlery:'10',sweet:true,weight:'2500'}],
        detImages:['13_1.jpg','13_2.jpg'],
        aboutFood:[{a1:'淡奶油',b1:'安佳/铁塔',c1:'韩国',
            a2:'白巧克力',b2:'雪花',c2:'比利时'}],
        aboutEat:'芝士口味'
    },
    {
        id:14,
        name:'牛乳大理石雪域双拼蛋糕',
		enName:'Milk & Marble Cheesecake',
        price:'198.00',
        isRecommend:false,
        isNews:false,
        isBlast:false,
        isHot:false,
        isSign:false,
        isSale:false,
        isPrompt:true,
        isLimit:false,
        isStand:false,
        images:['14.jpg'],
        norms:[{offer:'2-4',price:'198',content:'13*13',cutlery:'5',sweet:true,weight:'400'},
            {offer:'5-8',price:'298',content:'17*17',cutlery:'10',sweet:true,weight:'700'},
            {offer:'10-12',price:'458',content:'22*22',cutlery:'15',sweet:true,weight:'1200'},
            {offer:'15-20',price:'756',content:'31*31',cutlery:'10',sweet:true,weight:'2350'}],
        detImages:['14_1.jpg','14_2.jpg'],
        aboutFood:[{a1:'淡奶油',b1:'Anchor',c1:'新西兰',a2:'巧克力',b2:'嘉利宝/贝可拉',c2:'比利时'}],
        aboutEat:'芝士口味'
    },
    {
        id:15,
        name:'牛乳钻石雪域双拼蛋糕',
		enName:'Milk & Marble Cheesecake',
        price:'198.00',
        isRecommend:'false',
        isNews:false,
        isBlast:false,
        isHot:false,
        isSign:false,
        isSale:false,
        isPrompt:true,
        isLimit:false,
        isStand:false,
        images:['15.jpg'],
        norms:[{offer:'2-4',price:'198',content:'13*13',cutlery:'5',sweet:true,weight:'520'},
            {offer:'5-8',price:'298',content:'17*17',cutlery:'10',sweet:true,weight:'950'},
            {offer:'10-12',price:'458',content:'22*22',cutlery:'15',sweet:true,weight:'1580'},
            {offer:'15-20',price:'756',content:'31*31',cutlery:'10',sweet:true,weight:'3100'}],
        detImages:['15_1.jpg','15_2.jpg'],
        aboutFood:[{a1:'淡奶油',b1:'Anchor',c1:'新西兰',
            a2:'巧克力',b2:'嘉利宝/贝可拉',c2:'比利时'}],
        aboutEat:'芝士口味'
    },
    {
        id:16,
        name:'牛乳芒果雪域双拼蛋糕 Milk & Marble Cheesecake',
		enName:'Milk & Marble Cheesecake',
        price:'198.00',
        isRecommend:false,
        isNews:false,
        isBlast:false,
        isHot:false,
        isSign:false,
        isSale:false,
        isPrompt:true,
        isLimit:false,
        isStand:false,
        images:['16.jpg'],
        norms:[{offer:'2-4',price:'198',content:'13*13',cutlery:'5',sweet:true,weight:'450'},
            {offer:'5-8',price:'298',content:'17*17',cutlery:'10',sweet:true,weight:'800'},
            {offer:'10-12',price:'458',content:'22*22',cutlery:'15',sweet:true,weight:'1300'},
            {offer:'15-20',price:'756',content:'31*31',cutlery:'10',sweet:true,weight:'2500'}],
        detImages:['16_1.jpg','16_2.jpg'],
        aboutFood:[{a1:'无盐黄油',b1:'Anchor',c1:'新西兰',
            a2:'白巧克力',b2:'嘉利宝/贝可拉',c2:'比利时'}],
        aboutEat:'芝士口味'
    },
    {
        id:17,
        name:'牛乳蓝莓雪域双拼蛋糕',
		enName:'Milk & Marble Cheesecake',
        price:'198.00',
        isRecommend:false,
        isNews:false,
        isBlast:false,
        isHot:false,
        isSign:false,
        isSale:false,
        isPrompt:true,
        isLimit:false,
        isStand:false,
        images:['1.jpg'],
        norms:[{offer:'2-4',price:'198',content:'13*13',cutlery:'5',sweet:true,weight:'420'},
            {offer:'5-8',price:'298',content:'17*17',cutlery:'10',sweet:true,weight:'720'},
            {offer:'10-12',price:'458',content:'22*22',cutlery:'15',sweet:true,weight:'1200'},
            {offer:'15-20',price:'756',content:'31*31',cutlery:'10',sweet:true,weight:'2450'}],
        detImages:['17_1.jpg','17_2.jpg'],
        aboutFood:[{a1:'无盐黄油',b1:'Anchor',c1:'新西兰',a2:'巧克力',b2:'嘉利宝/贝可拉',c2:'比利时'}],
        aboutEat:'芝士口味'
    },
    {
        id:18,
        name:'蓝莓大理石雪域双拼蛋糕',
		enName:'Blueberry & Marble Cheesecake',
        price:'198.00',
        isRecommend:false,
        isNews:false,
        isBlast:false,
        isHot:false,
        isSign:false,
        isSale:false,
        isPrompt:true,
        isLimit:false,
        isStand:false ,
        images:['18.jpg'],
        norms:[{offer:'2-4',price:'198',content:'13*13',cutlery:'5',sweet:true,weight:'400'},
            {offer:'5-8',price:'298',content:'17*17',cutlery:'10',sweet:true,weight:'700'},
            {offer:'10-12',price:'458',content:'22*22',cutlery:'15',sweet:true,weight:'1200'},
            {offer:'15-20',price:'756',content:'31*31',cutlery:'10',sweet:true,weight:'2350'}],
        detImages:['18_1.jpg','18_2.jpg'],
        aboutFood:[{a1:'无盐黄油',b1:'Anchor',c1:'新西兰',
            a2:'巧克力',b2:'嘉利宝/贝可拉',c2:'比利时'}],
        aboutEat:'芝士口味、芝士口味'
    },
    {
        id:19,
        name:'双莓提拉米苏乐脆蛋糕',
		enName:'Raspberry Tiramisu Crispy',
        price:'198.00',
        isRecommend:false,
        isNews:false,
        isBlast:false,
        isHot:false,
        isSign:false,
        isSale:false,
        isPrompt:false,
        isLimit:false,
        isStand:false,
        images:['19.jpg','19b.jpg'],
        norms:[{offer:'2-4',price:'198.00',content:'13*13',cutlery:'5',sweet:true,weight:'430'},
            {offer:'5-8',price:'298.00',content:'17*17',cutlery:'10',sweet:true,weight:'750'},
            {offer:'10-12',price:'458.00',content:'22*22',cutlery:'15',sweet:true,weight:'1150'},
            {offer:'15-20',price:'756.00',content:'31*31',cutlery:'20',sweet:true,weight:'2250'}],
        detImages:['19_1.jpg','19_2.jpg'],
        p:'包裹浪漫的红色巧克力喷砂，编织每一口滋味的梦幻；草莓与桑莓的酸甜果味碰撞，擦出清新甜蜜的纯真乐趣，交织酥香与芝士奶油的绵密浓郁，口口留香，唇齿缠绵。浪漫的爱情故事，在味蕾中浓情上演。',
        aboutFood:[{a1:'果茸',b1:'桑莓',c1:'法国',
            a2:'奶酪',b2:'马斯卡邦',c2:'意大利',
            a3:'草莓巧克力片',b3:'嘉利宝',c3:'比利时',
            a4:'可可薄脆片',b4:'可可百利',c4:'比利时'}],
        aboutEat:'芝士口味'
    },
    {
        id:20,
        name:'雪域蓝莓芝士蛋糕',
		enName:'Blueberry Cheesecake/Emily',
        price:'198.00',
        isRecommend:false,
        isNews:false,
        isBlast:false,
        isHot:true,
        isSign:false,
        isSale:false,
        isPrompt:false,
        isLimit:false,
        isStand:false,
        images:['20.jpg','20b.jpg'],
        norms:[{offer:'2-4',price:'198.00',content:'13*13',cutlery:'5',sweet:true,weight:'450'},
            {offer:'5-8',price:'298.00',content:'17*17',cutlery:'10',sweet:true,weight:'770'},
            {offer:'10-12',price:'458.00',content:'22*22',cutlery:'15',sweet:true,weight:'1250'},
            {offer:'15-20',price:'756.00',content:'31*31',cutlery:'20',sweet:true,weight:'2500'}],
        detImages:['20_1.jpg','20_2.jpg'],
        p:'你我心里都曾经有过一个天真、活泼的女孩。哭着哭着却笑了，酸的都是甜，没有丰盛的物质，却拥有富足的心灵。回想人生，总有令人留恋的酸甜。（鲜果因时令季节变化，会做适当调整)',
        aboutFood:[{a1:'黄油',b1:'安佳/铁塔',c1:'进口',
            a2:'芝士',b2:'MG/安佳',c2:'进口',
            a3:'淡奶油',b3:'铁塔/安佳',c3:'进口',
            a4:'幼砂糖',b4:'雪花',c4:'韩国',
            a5:'白巧克力',b5:'嘉利宝/贝可拉',c5:'比利时'}],
        aboutEat:'鲜果口味、芝士口味'
    },
    {
        id:21,
        name:'玫瑰雪域芝士蛋糕',
		enName:'Rose Cheesecake',
        price:'218.00',
        isRecommend:false,
        isNews:false,
        isBlast:false,
        isHot:true,
        isSign:false,
        isSale:false,
        isPrompt:false,
        isLimit:false,
        isStand:false,
        images:['21.jpg','21b.jpg'],
        norms:[{offer:'2-4',price:'218.00',content:'13*13',cutlery:'5',sweet:true,weight:'420'},
            {offer:'5-8',price:'336.00',content:'17*17',cutlery:'10',sweet:true,weight:'760'},
            {offer:'10-12',price:'504.00',content:'22*22',cutlery:'15',sweet:true,weight:'1200'},
            {offer:'15-20',price:'840.00',content:'31*31',cutlery:'20',sweet:true,weight:'2450'}],
        detImages:['21_1.jpg','21_2.jpg'],
        p:'一片玫瑰的海洋，映衬着少男少女那纯净的心境。这么多朵玫瑰花，总像有数不清的芬芳思念，诉不尽的感恩眷恋，所有声音都在轻声呢喃着誓约长久。',
        aboutFood:[{a1:'芝士',b1:'MG/安佳',c1:'进口',
            a2:'黄油',b2:'安佳/铁塔',c2:'进口',
            a3:'白巧克力',b3:'嘉利宝/贝可拉',c3:'比利时',
            a4:'淡奶油',b4:'铁塔/安佳',c4:'进口',
            a5:'幼砂糖',b5:'雪花',c5:'韩国'}],
        aboutEat:'芝士口味、奶油口味'
    },
    {
        id:22,
        name:'巧克力松露蛋糕',
		enName:'Chocolate Marquise',
        price:'218.00',
        isRecommend:false,
        isNews:false,
        isBlast:false,
        isHot:false,
        isSign:false,
        isSale:false,
        isPrompt:false,
        isLimit:false,
        isStand:false,
        images:['22.jpg','22b.jpg'],
        norms:[{offer:'2-4',price:'218.00',content:'13*13',cutlery:'5',sweet:true,weight:'370'},
            {offer:'5-8',price:'336.00',content:'17*17',cutlery:'10',sweet:true,weight:'660'},
            {offer:'10-12',price:'504.00',content:'22*22',cutlery:'15',sweet:true,weight:'1050'},
            {offer:'15-20',price:'840.00',content:'31*31',cutlery:'20',sweet:true,weight:'2050'}],
        detImages:['22_1.jpg','22_2.jpg'],
        p:'这浓郁芳香，就像打开法国凡尔赛宫的大门。皇家园林的宏伟对称，玛莉皇后的瑰丽奢华，夜夜笙歌的乐韵… 一切，隐没于过去，遗下繁星、香气、味道，流传至今。',
        aboutFood:[{a1:'黑巧克力',b1:'嘉利宝/贝可拉',c1:'比利时',
            a2:'黄油',b2:'安佳/铁塔',c2:'进口',
            a3:'淡奶油',b3:'安佳/铁塔',c3:'进口',
            a4:'幼砂糖',b4:'雪花',c4:'韩国',
            a5:'全脂牛奶',b5:'得乐思/爱氏晨曦',c5:'法国/德国'}],
        aboutEat:'巧克力味'
    },
    {
        id:23,
        name:'环游世界·春夏季蛋糕',
		enName:'Around The World Cake',
        price:'218.00',
        isRecommend:false,
        isNews:false,
        isBlast:false,
        isHot:false,
        isSign:false,
        isSale:false,
        isPrompt:false,
        isLimit:false,
        isStand:false,
        images:['23.jpg','23b.jpg'],
        norms:[{offer:'2-4',price:'218.00',content:'13*13',cutlery:'5',sweet:true,weight:'400'},
            {offer:'5-8',price:'336.00',content:'17*17',cutlery:'10',sweet:true,weight:'700'},
            {offer:'10-12',price:'504.00',content:'22*22',cutlery:'15',sweet:true,weight:'1000'},
            {offer:'15-20',price:'840.00',content:'31*31',cutlery:'20',sweet:true,weight:'2000'}],
        detImages:['23_1.jpg','23_2.jpg'],
        p:'惊喜，是任性送给我的礼物。随心、随性、随感觉到处游历，每次都有新发现。惊喜，不用刻意安排。又或者，上天早已安排， 怎样，都好，就随意一点，任性一次吧。',
        aboutFood:[{a1:'牛奶巧克力',b1:'嘉利宝',c1:'比利时',
            a2:'乳脂奶油',b2:'铁塔',c2:'法国',
            a3:'马斯卡布尼芝士',b3:'琪雷萨',c3:'意大利'
        }],
        aboutEat:'慕斯口味'
    },
    {
        id:24,
        name:'草莓拿破仑蛋糕',
		enName:'Strawberry Mille-feuilles',
        price:'198.00',
        isRecommend:false,
        isNews:false,
        isBlast:false,
        isHot:false,
        isSign:false,
        isSale:false,
        isPrompt:false,
        isLimit:false,
        isStand:false,
        images:['24.jpg','24b.jpg'],
        norms:[{offer:'2-4',price:'198.00',content:'13*13',cutlery:'5',sweet:true,weight:'480'},
            {offer:'5-8',price:'298.00',content:'17*17',cutlery:'10',sweet:true,weight:'1000'},
            {offer:'10-12',price:'458.00',content:'22*22',cutlery:'15',sweet:true,weight:'1500'},
            {offer:'15-20',price:'756.00',content:'31*31',cutlery:'20',sweet:true,weight:'2450'}],
        detImages:['24_1.jpg','24_2.jpg'],
        p:'盒子上娇艳欲滴的红宝石，令人无法移开目光。像潘多拉的盒子，吸引好奇的味蕾。清脆的声音，没有惊醒少女的梦。（鲜果因时令季节变化，会做适当调整）',
        aboutFood:[{a1:'新鲜草莓',b1:'精选',c1:'-',
            a2:'淡奶油',b2:'铁塔/安佳',c2:'进口',
            a3:'黄油',b3:'铁塔/安佳',c3:'进口',
            a4:'幼砂糖',b4:'雪花',c4:'韩国',
            a5:'杏果酱',b5:'英雄',c5:'瑞士',
            a6:'全脂牛奶',b6:'爱氏晨曦',c6:'进口',
            a7:'朗姆酒',b7:'船长',c7:'英国'}],
        aboutEat:'拿破仑味、鲜果口味'
    },
    {
        id:25,
        name:'蓝莓拿破仑蛋糕',
		enName:'Blueberry Mille-feuilles',
        price:'198.00',
        isRecommend:false,
        isNews:false,
        isBlast:false,
        isHot:false,
        isSign:false,
        isSale:false,
        isPrompt:false,
        isLimit:false,
        isStand:false,
        images:['25.jpg','25b.jpg'],
        norms:[{offer:'2-4',price:'198.00',content:'13*13',cutlery:'5',sweet:true,weight:'450'},
            {offer:'5-8',price:'298.00',content:'17*17',cutlery:'10',sweet:true,weight:'950'},
            {offer:'10-12',price:'458.00',content:'22*22',cutlery:'15',sweet:true,weight:'1450'},
            {offer:'15-20',price:'756.00',content:'31*31',cutlery:'20',sweet:true,weight:'2450'}],
        detImages:['25_1.jpg','25_2.jpg'],
        p:'时而微笑，时而俏皮，时而乐开怀。生活本是多姿多彩，层层叠叠。第一层是欢乐，第二层是幸福，第三层是期待……第一千层，依然是微笑着面对人生。（鲜果因时令季节变化，会做适当调整）',
        aboutFood:[{a1:'蓝莓',b1:'精选',c1:'全球',
            a2:'淡奶油',b2:'铁塔/安佳',c2:'进口',
            a3:'黄油',b3:'铁塔/安佳',c3:'进口',
            a4:'幼砂糖',b4:'雪花',c4:'韩国',
            a5:'全脂牛奶',b5:'得乐思/爱氏晨曦',c5:'法国/德国'}],
        aboutEat:'拿破仑味、鲜果口味'
    },
    {
        id:26,
        name:'莓果绵绵蛋糕',
		enName:'Strawberry Cream Cake',
        price:'218.00',
        isRecommend:false,
        isNews:false,
        isBlast:false,
        isHot:true,
        isSign:false,
        isSale:false,
        isPrompt:false,
        isLimit:false,
        isStand:false,
        images:['26.jpg','26b.jpg'],
        norms:[{offer:'2-4',price:'218.00',content:'13*13',cutlery:'5',sweet:true,weight:'500'},
            {offer:'5-8',price:'336.00',content:'17*17',cutlery:'10',sweet:true,weight:'700'},
            {offer:'10-12',price:'504.00',content:'22*22',cutlery:'15',sweet:true,weight:'1000'}],
        detImages:['26_1.jpg','26_2.jpg'],
        p:'高雅奢华的皇家舞会徐徐拉开帷幕，璀璨灯光下公主的裙摆随着音乐偏偏旋转。少女的心动一如草莓的鲜红热烈，在浪漫起伏中，如梦般荡漾开来。',
        aboutFood:[{a1:'淡奶油',b1:'铁塔/安佳',c1:'新西兰',
            a2:'全脂牛奶',b2:'得乐思/爱氏晨曦',c2:'法国/德国'}],
        aboutEat:'奶油口味、鲜果口味'
    },
    {
        id:27,
        name:'唯·歌剧院蛋糕',
		enName:'Le Opera',
        price:'218.00',
        isRecommend:false,
        isNews:false,
        isBlast:false,
        isHot:false,
        isSign:false,
        isSale:false,
        isPrompt:false,
        isLimit:false,
        isStand:false,
        images:['27.jpg','27b.jpg'],
        norms:[{offer:'2-4',price:'218.00',content:'13*13',cutlery:'5',sweet:true,weight:'420'},
            {offer:'5-8',price:'336.00',content:'17*17',cutlery:'10',sweet:true,weight:'760'},
            {offer:'10-12',price:'504.00',content:'22*22',cutlery:'15',sweet:true,weight:'1160'},
            {offer:'15-20',price:'840.00',content:'31*31',cutlery:'20',sweet:true,weight:'2360'}],
        detImages:['27_1.jpg','27_2.jpg'],
        p:'午夜的巴黎，晶莹的水晶吊灯，华丽的歌剧院大厅 。仿佛穿越了一个世纪。一切变得这么美妙，让人期待一场，浪漫的邂逅。（鲜果因时令季节变化，会做适当调整）',
        aboutFood:[{a1:'全脂牛奶',b1:'爱氏晨曦',c1:'进口',
            a2:'黄油',b2:'安佳/铁塔',c2:'进口',
            a3:'白巧克力',b3:'嘉利宝/贝可拉',c3:'比利时'}],
        aboutEat:'鲜果口味'
    },
    {
        id:28,
        name:'上上签蛋糕',
		enName:'Lucky',
        price:'258.00',
        isRecommend:false,
        isNews:false,
        isBlast:false,
        isHot:false,
        isSign:false,
        isSale:false,
        isPrompt:false,
        isLimit:false,
        isStand:false,
        images:['wj28_1.jpg','wj28_2.jpg'],
        norms:[{offer:'2-4',price:'258.00',content:'16*16',cutlery:'5',sweet:true,weight:'545'}],
        detImages:['wj28_3.jpg','wj28_4.jpg'],
        p:'爱吃甜食的人运气都不错！甜美的草莓加上松软的蛋糕，吃上一口，有一种中乐透般的幸福感。',
        aboutFood:[{a1:'淡奶油',b1:'Anchor',c1:'新西兰',
            a2:'无盐黄油',b2:'Anchor',c2:'新西兰',
            a3:'黑巧克力',b3:'Callebaut',c3:'比利时',
            a4:'可可薄脆片',b4:'BACKEUROP',c4:'法国',
            a5:'马斯卡布尼奶酪',b5:'sterilgar', c5:'意大利',
            a6:'奥世纽扣型调温纯脂苦甜巧克力',b6:'Patissiec',c6:'新加坡'}],
        aboutEat:'慕斯口味'
    },
    {
        id:29,
        name:"诺心花园*夏至蛋糕",
		enName:"Le Cake's Garden/ Summe",
        price:'218.00',
        isRecommend:false,
        isNews:false,
        isBlast:false,
        isHot:false,
        isSign:false,
        isSale:false,
        isPrompt:false,
        isLimit:false,
        isStand:false,
        images:['wj30_1.jpg','wj30_2.jpg'],
        norms:[ {offer:'2-4',price:'218.00',content:'16*16',cutlery:'5',sweet:true,weight:'545'}],
        detImages:['wj29_2.jpg','wj29_3.jpg'],
        p:'朋友，是张拼图。他如酒精般挥洒个性，他如芒果的清新甘饴，他如脆饼般爽朗，他如浓滑芝士一样细腻，大家有说不完的故事，每次回味，都是金黄色夏日的温暖。',
        aboutFood:[],
        aboutEat:'慕斯口味'
    },
    {
        id:30,
        name:'粉色玫瑰森林蛋糕',
		enName:"Rose Garden",
        price:'218.00',
        isRecommend:false,
        isNews:false,
        isBlast:false,
        isHot:false,
        isSign:false,
        isSale:false,
        isPrompt:false,
        isLimit:false,
        isStand:false,
        images:['wj30_1.jpg','wj30_2.jpg'],
        norms:[{offer:'2-4',price:'218.00',content:'13*13',cutlery:'5',sweet:true,weight:'500'},
            {offer:'5-8',price:'336.00',content:'17*17',cutlery:'10',sweet:true,weight:'880'},
            {offer:'10-12',price:'504.00',content:'22*22',cutlery:'15',sweet:true,weight:'1380'},
            {offer:'15-20',price:'840.00',content:'31*31',cutlery:'10',sweet:true,weight:'2650'}],
        detImages:['wj30_3.jpg','wj30_4.jpg'],
        p:'森林被风吹过，都一一开了玫瑰。连花仙子都知道，有种相依为命的味道。牵手越过所有荆棘，把爱情放在玫瑰的森林里，世界变成了两个人的秘密花园。',
        aboutFood:[{a1:'巧克力',b1:'嘉利宝/贝可拉',c1:'比利时',
            a2:'淡奶油',b2:'铁塔/安佳',c2:'进口',
            a3:'樱桃白兰地',b3:'波士',c3:'荷兰',
            a4:'幼砂糖',b4:'雪花',c4:'韩国',
            a5:'全脂奶粉',b5:'得乐思/爱氏晨曦',c5:'法国/德国',
            a6:'可可粉',b6:'马天尼',c6:'荷兰'}],
        aboutEat:'芝士口味、奶油口味'
    },
    {
        id:31,
        name:'爱·发声蛋糕',
		enName:"Le Loves",
        price:'258.00',
        isRecommend:false,
        isNews:false,
        isBlast:false,
        isHot:false,
        isSign:false,
        isSale:false,
        isPrompt:false,
        isLimit:false,
        isStand:false,
        images:['wj31_1.jpg','wj31_2.jpg'],
        norms:[{offer:'2-4',price:'258.00',content:'13*13',cutlery:'5',sweet:true,weight:'400'}],
        detImages:['wj31_3.jpg','wj31_4.jpg'],
        p:'花瓣在呢喃的耳语里甜美的绽放，吐露着之前不曾开放过的另一段幽情。就是此刻，倾听专属的花语，让那些未曾诉说的情愫，一遍一遍萦绕在耳畔。',
        aboutFood:[{a1:'无盐黄油',b1:'Anchor',c1:'新西兰',
            a2:'可可薄脆片',b2:'BACKEUROP',c2:'法国',
            a3:'淡奶油',b3:'Anchor',c3:'新西兰',
            a4:'黑巧克力',b4:'Callebaut',c4:'比利时',
            a5:'白巧克力',b5:'VANHOUTEN',c5:'新加坡'}],
        aboutEat:'巧克力口味'
    },
    {
        id:32,
        name:'芙洛拉蛋糕',
		enName:"Flora",
        price:'368.00',
        isRecommend:false,
        isNews:false,
        isBlast:false,
        isHot:false,
        isSign:false,
        isSale:false,
        isPrompt:false,
        isLimit:true,
        isStand:false,
        images:['wj32_1.jpg','wj32_2.jpg'],
        norms:[{offer:'2-4',price:'368.00',content:'13*13',cutlery:'5',sweet:true,weight:'454'}],
        detImages:['wj32_3.jpg','wj32_4.jpg'],
        p:'花神Flora，传说她头戴花冠，身穿缀满天竺葵、鸢尾的衣裙，所到之处，百花齐放。就像见到你时那一刻的怦然心动，心就这样花漾般绽放，爱情也随之盛开。',
        aboutFood:[{a1:'香草戚风蛋糕胚',b1:'自制',c1:'中国',
            a2:'脆糖',b2:'自制',c2:'中国',
            a3:'奶油',b3:'自制',c3:'中国',
            a4:'黄油',b4:'自制',c4:'中国'}],
        aboutEat:'奶油口味'
    },
    {
        id:33,
        name:'海盐乳酪芝士蛋糕',
		enName:"Parmesan Cheesecake",
        price:'198.00',
        isRecommend:false,
        isNews:false,
        isBlast:false,
        isHot:false,
        isSign:false,
        isSale:false,
        isPrompt:false,
        isLimit:false,
        isStand:false,
        images:['wj33_1.jpg','wj33_2.jpg'],
        norms:[{offer:'2-4',price:'198.00',content:'13*13',cutlery:'5',sweet:true,weight:'454'},
            {offer:'5-8',price:'298.00',content:'17*17',cutlery:'10',sweet:true,weight:'800'},
            {offer:'10-12',price:'458.00',content:'22*22',cutlery:'15',sweet:true,weight:'1250'},
            {offer:'15-20',price:'756.00',content:'31*31',cutlery:'10',sweet:true,weight:'2200'}],
        detImages:['wj33_3.jpg','wj33_4.jpg'],
        p:'充满回忆的味道，总令人难以忘怀。那是西西里岛的风味，充满渔夫自然不造作的热情， 与素未谋面的我，分享渔获，分享喜悦。',
        aboutFood:[{a1:'巴马芝士粉',b1:'卡夫',c1:'美国',
            a2:'芝士',b2:'MG/安佳',c2:'进口',
            a3:'黄油',b3:'安佳/铁塔',c3:'进口',
            a4:'幼砂糖',b4:'雪花',c4:'韩国'}],
        aboutEat:'芝士口味'
    },
    {
        id:34,
        name:'你好米菲蛋糕',
		enName:"hallo miffy",
        price:'218.00',
        isRecommend:false,
        isNews:false,
        isBlast:false,
        isHot:false,
        isSign:false,
        isSale:false,
        isPrompt:false,
        isLimit:false,
        isStand:false,
        images:['wj34_1.jpg','wj34_2.jpg'],
        norms:[{offer:'2-4',price:'218.00',content:'13*13',cutlery:'5',sweet:true,weight:'454'}],
        detImages:['wj34_3.jpg','wj34_4.jpg'],
        p:'松软的红丝绒搭配绵密轻柔的慕斯，编织出了童年纯真的梦想，单纯而美好，巧克力的甜蜜锁住孩童时最肆意的欢乐绽放，萌动俏皮的miffy，将用聪明、单纯、简单、美好为童年定格最甜蜜的时刻。',
        aboutFood:[{a1:'稀奶油',b1:'爱乐薇',c1:'法国',
            a2:'芝士',b2:'安佳',c2:'新西兰',
            a3:'奶酪',b3:'琪雷萨',c3:'意大利',
            a4:'巧克力',b4:'奥世',c4:'新加坡',
            a5:'牛奶',b5:'得乐思',c5:'法国'}],
        aboutEat:'慕斯口味、芝士口味'
    },
    {
        id:35,
        name:'芒果雪域芝士蛋糕',
		enName:"Mango Cheesecake",
        price:'218.00',
        isRecommend:false,
        isNews:false,
        isBlast:false,
        isHot:false,
        isSign:false,
        isSale:false,
        isPrompt:false,
        isLimit:false,
        isStand:false,
        images:['wj35_1.jpg','wj35_2.jpg'],
        norms:[{offer:'2-4',price:'218.00',content:'13*13',cutlery:'5',sweet:true,weight:'500'},
            {offer:'5-8',price:'336.00',content:'17*17',cutlery:'10',sweet:true,weight:'850'},
            {offer:'10-12',price:'504.00',content:'22*22',cutlery:'15',sweet:true,weight:'1450'},
            {offer:'15-20',price:'840.00',content:'31*31',cutlery:'10',sweet:true,weight:'2750'}],
        detImages:['wj35_3.jpg','wj35_4.jpg'],
        p:'阿尔卑斯峰顶的纯雪遇上东南亚的暖风，交织一首冰与火的歌，呢喃着旅途的故事，变成了你的样子。',
        aboutFood:[{a1:'黄油',b1:'安佳/铁塔',c1:'进口',
            a2:'全脂牛奶',b2:'爱氏晨曦',c2:'进口',
            a3:'淡奶油',b3:'安佳/铁塔',c3:'进口',
            a4:'芒果',b4:'精选',c4:'全球',
            a5:'芝士',b5:'安佳',c5:'新西兰'}],
        aboutEat:'鲜果口味、芝士口味'
    },
    {
        id:36,
        name:'榛子千层拿破仑蛋糕',
		enName:"Hazelnut Mille-feuilles",
        price:'198.00',
        isRecommend:false,
        isNews:false,
        isBlast:false,
        isHot:false,
        isSign:false,
        isSale:false,
        isPrompt:false,
        isLimit:false,
        isStand:false,
        images:['wj36_1.jpg','wj36_2.jpg'],
        norms:[{offer:'2-4',price:'198.00',content:'13*13',cutlery:'5',sweet:true,weight:'440'},
            {offer:'5-8',price:'298.00',content:'17*17',cutlery:'10',sweet:true,weight:'920'},
            {offer:'10-12',price:'458.00',content:'22*22',cutlery:'15',sweet:true,weight:'1400'},
            {offer:'15-20',price:'756.00',content:'31*31',cutlery:'10',sweet:true,weight:'2280'}],
        detImages:['wj36_3.jpg','wj36_4.jpg'],
        p:'人生千面，凝刻着岁月，如风流转，遇到你，看见他，痴缠在笑与泪水间，有时迸发激情，有时恬静淡然。相遇、牵手、遗忘、愤恨，人生碰撞了彼此，才能活出层层叠叠的精彩人生。',
        aboutFood:[{a1:'黄油',b1:'安佳/铁塔',c1:'进口',
            a2:'黑朗姆酒',b2:'船长',c2:'英国',
            a3:'榛果酱',b3:'嘉利宝/贝可拉',c3:'比利时',
            a4:'淡奶油',b4:'安佳/铁塔',c4:'进口',
            a5:'幼砂糖',b5:'雪花',c5:'韩国'}],
        aboutEat:'拿破仑味'
    },
    {
        id:37,
        name:'芒果千层拿破仑蛋糕',
		enName:"Mango Mille-feuilles",
        price:'198.00',
        isRecommend:false,
        isNews:false,
        isBlast:false,
        isHot:false,
        isSign:false,
        isSale:false,
        isPrompt:false,
        isLimit:false,
        isStand:false,
        images:['37.jpg','37b.jpg'],
        norms:[ {'offer':'4-6','content':'13*13','cutlery':'5','sweet':true,price:'198.00','weight':'480'},
                {'offer':'5-8','content':'17*17','cutlery':'10','sweet':true,price:'298.00','weight':'1000'},
                {'offer':'10-12','content':'22*22','cutlery':'15','sweet':true,price:'458.00','weight':'1500'},
                {'offer':'15-20','content':'31*31','cutlery':'20','sweet':true,price:'756.00','weight':'2480'}
        ],
        detImages:['37_1.jpg','37_2.jpg'],
        p:'太阳花，从法国的南部开到花都。 欢迎盛夏。巴黎小街填满了阳光，像拿破仑蛋糕薄脆之间的浓滑奶油。这……是我爱上仲夏的理由。（鲜果因时令季节变化，会做适当调整）',
        aboutFood:[{a1:'芒果',b1:'精选',c1:'全球',
                    a2:'淡奶油',b2:'铁塔/安佳',c2:'进口',
                    a3:'黄油',b3:'铁塔/安佳',c3:'进口',
                    a4:'幼砂糖',b4:'雪花',c4:'韩国',
                    a5:'全脂牛奶',b5:'得乐思/爱氏晨曦',c5:'法国/德国'}],
        aboutEat:'拿破仑味，鲜果口味'
    },
    {
        id:38,
        name:'罗马假日',
		enName:"Mango Tango",
        price:'218.00',
        isRecommend:false,
        isNews:false,
        isBlast:false,
        isHot:false,
        isSign:false,
        isSale:false,
        isPrompt:false,
        isLimit:false,
        isStand:false,
        images:['38.jpg','38b.jpg'],
        norms:[ {offer:'4-6',content:'17*17',cutlery:'10',sweet:true,price:'218.00',weight:'727'} ],
        detImages:['38_1.jpg','38_2.jpg'],
        p:'跟着音乐灵动摇曳的裙摆，踏着节奏足尖轻快的步伐，每一个节拍都在欢呼着假日的喜悦。有人说，倘若快乐一但如阳光般照进心房，即便笑声是短暂的，幸福却可以是永恒的。',
        aboutFood:[{a1:'牛奶',b1:'得乐思',c1:'法国',
                    a2:'幼砂糖',b2:'TS',c2:'韩国',
                    a3:'奶油芝士',b3:'安佳',c3:'新西兰',
                    a4:'白巧克力',b4:'嘉利宝',c4:'比利时',
                    a5:'百香果泥',b5:'宝茸',c5:'法国',
                    a6:'黄油',b6:'安佳',c6:'新西兰',
                    a7:'淡奶油',b7:'铁塔',c7:'法国',
                    a8:'稀奶油',b8:'roselle',c8:'英国'}],
        aboutEat:'鲜果口味，芝士口味'
    },
    {
        id:39,
        name:'繁星之吻',
		enName:"Blueberry Kiss",
        price:'218.00',
        isRecommend:false,
        isNews:false,
        isBlast:false,
        isHot:false,
        isSign:false,
        isSale:false,
        isPrompt:false,
        isLimit:false,
        isStand:false,
        images:['39.jpg'],
        norms:[ {offer:'4-6',content:'17*17',cutlery:'10',sweet:true,price:'218.00',weight:'727'} ],
        detImages:['39_1.jpg','39_2.jpg'],
        p:'这世界色彩太多快乐也变得无所适从，而纯味奶油与酸甜蓝莓的混搭却能治愈快乐缺乏症。点缀在蓝紫色奶油上的颗颗果肉，犹如星空成为了每个人心中最神秘的向往。',
        aboutFood:[{a1:'无盐黄油',b1:'Anchor',c1:'新西兰',
                    a2:'淡奶油',b2:'铁塔',c2:'法国',
                    a3:'稀奶油',b3:'罗塞',c3:'英国'}],
        aboutEat:'鲜果口味，芝士口味'
    },
    {
        id:40,
        name:'芒果芒果蛋糕',
		enName:"Mango Mango",
        price:'198.00',
        isRecommend:false,
        isNews:false,
        isBlast:false,
        isHot:false,
        isSign:false,
        isSale:false,
        isPrompt:false,
        isLimit:false,
        isStand:false,
        images:['40.jpg','40b.jpg'],
        norms:[ {offer:'2-4',content:'13*13',cutlery:'5',sweet:true,price:'198.00',weight:'350'},
                {offer:'5-8',content:'17*17',cutlery:'10',sweet:true,price:'298.00',weight:'750'},
                {offer:'10-12',content:'22*22',cutlery:'15',sweet:true,price:'458.00',weight:'1100'},
                {offer:'15-20',content:'31*31',cutlery:'20',sweet:true,price:'756.00',weight:'1700'} ],
        detImages:['40_1.jpg','40_2.jpg'],
        p:'到东南亚，是为了追逐所有金黄色。阳光，一如以往的金黄。大海，折射着一片金黄色的清澄。沙滩，是金黄色的幼滑。空气，泛着金黄色自有的香甜。（鲜果因时令季节变化，会做适当调整）',
        aboutFood:[{a1:'淡奶油',b1:'铁塔/安佳',c1:'进口',
                    a2:'芒果',b2:'精选',c2:'全球',
                    a3:'芒果果蓉',b3:'卡福洛/宝茸',c3:'法国',
                    a4:'幼砂糖',b4:'雪花',c4:'韩国',
                    a5:'全脂牛奶',b5:'得乐思/爱氏晨曦',c5:'法国/德国'}],
        aboutEat:'鲜果味'
    },
    {
        id:41,
        name:'杨枝甘露蛋糕',
		enName:"Mango Pomelo Mousse",
        price:'218.00',
        isRecommend:false,
        isNews:false,
        isBlast:false,
        isHot:false,
        isSign:false,
        isSale:false,
        isPrompt:false,
        isLimit:false,
        isStand:false,
        images:['41.jpg','41b.jpg'],
        norms:[ {offer:'2-4',content:'13*13',cutlery:'5',sweet:true,price:'218.00',weight:'550'},
                {offer:'5-8',content:'17*17',cutlery:'10',sweet:true,price:'336.00',weight:'950'},
                {offer:'10-12',content:'22*22',cutlery:'15',sweet:true,price:'504.00',weight:'1600'},
                {offer:'15-20',content:'31*31',cutlery:'20',sweet:true,price:'840.00',weight:'3000'} ],
        detImages:['41_1.jpg','41_2.jpg'],
        p:'法国米其林三星餐厅Le Doyen总厨克里斯汀·史奎尔先生专为诺心LECAKE三周年庆，历时半年精心调研，特别制作符合中国人喜好的杨枝甘露口味蛋糕，呈上满满幸福的味道。（鲜果因时令季节变化，会做适当调整）',
        aboutFood:[{a1:'全脂牛奶',b1:'爱氏晨曦',c1:'进口',
                    a2:'幼砂糖',b2:'雪花',c2:'韩国',
                    a3:'奶油奶酪',b3:'kin',c3:'法国',
                    a4:'椰浆',b4:'俏果',c4:'泰国',
                    a5:'椰子味朗姆酒',b5:'马利宝',c5:'西班牙',
                    a6:'淡奶油',b6:'铁塔',c6:'法国',
                    a7:'白巧克力',b7:'宝嘉丽',c7:'比利时'}],
        aboutEat:'鲜果口味、慕斯口味'
    },
    {
        id:42,
        name:'女神·冰淇淋蛋糕',
		enName:"Strawberry Snow Bear",
        price:'298.00',
        isRecommend:false,
        isNews:false,
        isBlast:false,
        isHot:false,
        isSign:false,
        isSale:false,
        isPrompt:false,
        isLimit:false,
        isStand:false,
        images:['42.jpg','42b.jpg'],
        norms:[ {offer:'5-8',content:'17*14',cutlery:'10',sweet:true,price:'298.00',weight:'726'} ],
        detImages:['42_1.jpg','42_2.jpg'],
        p:'粉红的光泽透露慵懒的迷离，听一曲萨克斯吹奏的蓝调吧，只有如此才能将美释放得淋漓尽致，无可描摹的奢华完美，就在此刻呈现。',
        aboutFood:[{a1:'牛奶',b1:'爱氏晨曦/得乐思',c1:'进口',
                    a2:'幼砂糖',b2:'雪花',c2:'韩国',
                    a3:'可可粉',b3:'马天尼',c3:'荷兰',
                    a4:'淡奶油',b4:'铁塔',c4:'法国',
                    a5:'稀奶油',b5:'罗塞',c5:'英国',
                    a6:'葡萄糖',b6:'DGF',c6:'法国',
                    a7:'草莓巧克力',b7:'宝嘉丽',c7:'比利时',
                    a8:'白巧克力',b8:'宝嘉丽',c8:'比利时'}],
        aboutEat:'冰淇淋、巧克力味'
    },
    {
        id:43,
        name:'男神·冰淇淋蛋糕',
		enName:"Chocolate Snow Bear",
        price:'298.00',
        isRecommend:false,
        isNews:false,
        isBlast:false,
        isHot:false,
        isSign:false,
        isSale:false,
        isPrompt:false,
        isLimit:false,
        isStand:false,
        images:['43.jpg','43b.jpg'],
        norms:[ {offer:'5-8',content:'17*14',cutlery:'10',sweet:true,price:'298.00',weight:'726'} ],
        detImages:['43_1.jpg','43_2.jpg'],
        p:'随心而走的旅行，静观布拉格广场上纷飞而起的白鸽，朝许愿池里投下第五枚硬币时，所有美好的画面被定格。',
        aboutFood:[{a1:'无盐黄油',b1:'安佳',c1:'新西兰',
                    a2:'黑巧克力',b2:'宝嘉丽',c2:'比利时',
                    a3:'幼砂糖',b3:'雪花',c3:'韩国',
                    a4:'可可粉',b4:'马天尼',c4:'比利时',
                    a5:'淡奶油',b5:'铁塔',c5:'法国',
                    a6:'稀奶油',b6:'罗塞',c6:'英国'}],
        aboutEat:'冰淇淋、巧克力味'
    },
    {
        id:44,
        name:'芒果心愿盒蛋糕 ',
		enName:"Mango Box",
        price:'218.00',
        isRecommend:false,
        isNews:false,
        isBlast:false,
        isHot:false,
        isSign:false,
        isSale:false,
        isPrompt:false,
        isLimit:false,
        isStand:false,
        images:['44.jpg','44b.jpg'],
        norms:[ {offer:'2-4',content:'13*13',cutlery:'5',sweet:true,price:'218.00',weight:'480'},
                {offer:'5-8',content:'17*17',cutlery:'10',sweet:true,price:'336.00',weight:'860'},
                {offer:'10-12',content:'22*22',cutlery:'15',sweet:true,price:'504.00',weight:'1350'},
                {offer:'15-20',content:'31*31',cutlery:'20',sweet:true,price:'840.00',weight:'2550'} ],
        p:'记忆中熟悉的味道，激起心中的涟漪，酸甜可口的芒果与柚子在舌尖跳跃旋转，如同长滩岛沙滩上日落的风景，让人沉醉其中，仿佛时间就在这一秒定格。（鲜果因时令季节变化，会做适当调整）',
        aboutFood:[{a1:'淡奶油',b1:'铁塔/安佳',c1:'进口',
                    a2:'全脂牛奶',b2:'得乐思',c2:'法国',
                    a3:'芒果',b3:'精选',c3:'全球',
                    a4:'幼砂糖',b4:'雪花',c4:'韩国'}],
        aboutEat:'鲜果口味'
    },
    {
        id:45,
        name:'公主蛋糕',
		enName:"Prinecess Cakes", 
        price:'218.00',
        isRecommend:false,
        isNews:false,
        isBlast:false,
        isHot:false,
        isSign:false,
        isSale:false,
        isPrompt:false,
        isLimit:false,
        isStand:false,
        images:['45.jpg'],
        norms:[ {offer:'2-4',content:'13*13',cutlery:'5',sweet:true,price:'218.00',weight:'460'},
                {offer:'5-8',content:'17*17',cutlery:'10',sweet:true,price:'336.00',weight:'720'},
                {offer:'10-12',content:'22*22',cutlery:'15',sweet:true,price:'504.00',weight:'1100'},
                {offer:'15-20',content:'31*31',cutlery:'20',sweet:true,price:'840.00',weight:'2300'} ],
        p:'童年是一段像棉花糖一样柔软的记忆，人总叹息时日匆匆，带走了纯真的心境，却忘了童真带来的勇气，带领孩子，寻找内心的乐园。',
        aboutFood:[{a1:'淡奶油',b1:'铁塔/安佳',c1:'进口',a2:'荔枝果茸',b2:'卡福洛',c2:'法国',a3:'白砂糖',b3:'嘉利宝/贝可拉',c3:'比利时',a4:'幼砂糖',b4:'雪花',c4:'韩国'}],
        aboutEat:'巧克力味'
   },
    {
        id: 46,
        name: '王子蛋糕',
		enName:"Prince Cake", 
        price: '218.00',
        isRecommend: false,
        isNews: false,
        isBlast: false,
        isHot: false,
        isSign:false,
        isSale:false,
        isPrompt:false,
        isLimit:false,
        isStand:false,
        images:['tjl46_1.jpg','tjl46_2.jpg'],
        norms:[{offer:'2-4',price:'218.00',content:'13*13',cutlery:'5',sweet:true,weight:'380'},
            {offer:'5-8',price:'336.00',content:'17*17',cutlery:'10',sweet:true,weight:'800'},
            {offer:'10-12',price:'504.00',content:'22*22',cutlery:'15',sweet:true,weight:'1240'},
            {offer:'15-20',price:'840.00',content:'31*31',cutlery:'20',sweet:true,weight:'2000'}],
        detImages:['tjl46_3.jpg','tjl46_4.jpg'],
        p:'从前，黑森林里有一个王子，在纷扰的天空下发现单纯的童真，路上遇上了七色精灵，化作彩虹桥，王子踏上云端，决心寻找幸福的终点。',
        aboutFood:[{a1:'黑巧克力',b1:'嘉利宝/贝克拉',c1:'比利时',
            a2:'淡奶油',b2:'铁塔/安佳',c2:'进口',
            a3:'黄油',b3:'安佳/铁塔',c3:'进口',
            a4:'幼砂糖',b4:'雪花',c4:'韩国',
            a5:'樱桃白兰地',b5:'波士',c5:'荷兰'}],
        aboutEat:'巧克力味'
    },
    {
        id: 47,
        name: '巧克力四重奏蛋糕',
		enName:"Chocolate Quartet", 
        price: '198.00',
        isRecommend: false,
        isNews: false,
        isBlast: false,
        isHot: false,
        isSign: false,
        isSale: false,
        isPrompt: false,
        isLimit: false,
        isStand: false,
        images:['tjl47_1.jpg','tjl47_2.jpg'],
        norms:[{offer:'2-4',price:'198.00',content:'13*13',cutlery:'5',sweet:true,weight:'370'},
            {offer:'5-8',price:'298.00',content:'17*17',cutlery:'10',sweet:true,weight:'660'},
            {offer:'10-12',price:'458.00',content:'22*22',cutlery:'15',sweet:true,weight:'1050'},
            {offer:'15-20',price:'756.00',content:'31*31',cutlery:'20',sweet:true,weight:'2050'}],
        detImages:['tjl47_3.jpg','tjl47_4.jpg'],
        p:'奥地利的语言只有黑与白。足以奏出一切喜、怒、哀、乐、沉实澎湃的黑，明朗轻快的白，将一生化成悠长的一曲，随时回味、回味。',
        aboutFood:[{a1:'巧克力',b1:'嘉利宝/贝克拉',c1:'比利时',
            a2:'淡奶油',b2:'铁塔/安佳',c2:'进口',
            a3:'朗姆酒',b3:'船长',c3:'英国',
            a4:'幼砂糖',b4:'雪花',c4:'韩国',
            a5:'樱桃白兰地',b5:'波士',c5:'荷兰'}],
        aboutEat:'巧克力味、慕斯口味'
    },
    {
        id: 48,
        name: '和风抹茶红豆蛋糕',
		enName:"Matcha Red bean cake", 
        price: '198.00',
        isRecommend: false,
        isNews: false,
        isBlast: false,
        isHot: false,
        isSign: false,
        isSale: false,
        isPrompt: false,
        isLimit: false,
        isStand: false,
        images:['tjl48_1.jpg','tjl48_2.jpg'],
        norms:[{offer:'2-4',price:'198.00',content:'13*13',cutlery:'5',sweet:true,weight:'320'},
            {offer:'5-8',price:'298.00',content:'17*17',cutlery:'10',sweet:true,weight:'600'},
            {offer:'10-12',price:'458.00',content:'22*22',cutlery:'15',sweet:true,weight:'950'},
            {offer:'15-20',price:'756.00',content:'31*31',cutlery:'20',sweet:true,weight:'1980'}],
        detImages:['tjl48_3.jpg','tjl48_4.jpg'],
        p:'日式传统的风雅，为现代简约主义牵起涟漪。线与面的交错，谱出一段探戈，刚与柔，甘与醇，进进退退之间，没有对与错。',
        aboutFood:[{a1:'牛奶',b1:'爱氏晨曦',c1:'进口',
            a2:'幼砂糖',b2:'TS',c2:'韩国',
            a3:'淡奶油',b3:'罗塞/铁塔',c3:'进口',
            a4:'葡萄糖浆',b4:'DGF',c4:'法国',
            a5:'白巧克力',b5:'嘉利宝',c5:'比利时'}],
        aboutEat:'慕斯口味'
    },
    {
        id: 49,
        name: '梵尼兰开心花园蛋糕',
		enName:"Vanilla Happy Garden", 
        price: '218.00',
        isRecommend: false,
        isNews: false,
        isBlast: false,
        isHot: false,
        isSign: false,
        isSale: false,
        isPrompt: false,
        isLimit: false,
        isStand: false,
        images:['tjl49_1.jpg'],
        norms:[{offer:'2-4',price:'218.00',content:'13*13',cutlery:'5',sweet:true,weight:'320'},
            {offer:'5-8',price:'336.00',content:'17*17',cutlery:'10',sweet:true,weight:'600'},
            {offer:'10-12',price:'504.00',content:'22*22',cutlery:'15',sweet:true,weight:'1000'},
            {offer:'15-20',price:'840.00',content:'31*31',cutlery:'20',sweet:true,weight:'1980'}],
        detImages:['tjl49_2.jpg','tjl49_3.jpg'],
        p:'一颗掉进土耳其神秘花园的开心果，遇见浪漫的梵尼兰，魔幻般的缘分造就柔软的梦。现在它们相互交织与传递，只是想告诉你，此刻承载的不仅是美味，更是梦想。',
        aboutFood:[{a1:'开心果酱',b1:'嘉利宝',c1:'比利时',
            a2:'淡奶油',b2:'铁塔/安佳',c2:'进口',
            a3:'白巧克力',b3:'嘉利宝/贝克拉',c3:'比利时',
            a4:'幼砂糖',b4:'雪花',c4:'韩国'}],
        aboutEat:'慕斯口味'
    },
    {
        id: 50,
        name: '雪域大理石芝士蛋糕',
		enName:"Marble Cheesecake", 
        price: '198.00',
        isRecommend: false,
        isNews: false,
        isBlast: false,
        isHot: false,
        isSign: false,
        isSale: false,
        isPrompt: false,
        isLimit: false,
        isStand: false,
        images:['tjl50_1.jpg','tjl50_2.jpg'],
        norms:[{offer:'2-4',price:'198.00',content:'13*13',cutlery:'5',sweet:true,weight:'420'},
            {offer:'5-8',price:'298.00',content:'17*17',cutlery:'10',sweet:true,weight:'720'},
            {offer:'10-12',price:'458.00',content:'22*22',cutlery:'15',sweet:true,weight:'1200'},
            {offer:'15-20',price:'756.00',content:'31*31',cutlery:'20',sweet:true,weight:'2350'}],
        detImages:['tjl50_3.jpg','tjl50_4.jpg'],
        p:'简约的几何、原始的色调，却是不平凡的杰作。德国包豪斯设计往往是简单而有力。如琴键黑白之间合拍的跃动，谱出一段段震撼的乐曲。空气凝止，余韵仍萦绕不去。。',
        aboutFood:[{a1:'巧克力',b1:'嘉利宝/贝克拉',c1:'比利时',
            a2:'芝士',b2:'MG/安佳',c2:'进口',
            a3:'淡奶油',b3:'铁塔/安佳',c3:'进口',
            a4:'黄油',b4:'铁塔/安佳',c4:'进口',
            a5:'幼砂糖',b5:'雪花',c5:'韩国',
            a6:'巧克力酱',b6:'好时',c6:'美国'}],
        aboutEat:'芝士口味'
    },
    {
        id: 51,
        name: '核桃栗子蛋糕',
		enName:"Chestnut Walnut Mousse", 
        price: '218.00',
        isRecommend: false,
        isNews: false,
        isBlast: false,
        isHot: false,
        isSign: false,
        isSale: false,
        isPrompt: false,
        isLimit: false,
        isStand: false,
        images:['tjl51_1.jpg','tjl51_2.jpg'],
        norms:[{offer:'2-4',price:'218.00',content:'13*13',cutlery:'5',sweet:true,weight:'500'},
            {offer:'5-8',price:'336.00',content:'17*17',cutlery:'10',sweet:true,weight:'820'},
            {offer:'10-12',price:'504.00',content:'22*22',cutlery:'15',sweet:true,weight:'1350'},
            {offer:'15-20',price:'840.00',content:'31*31',cutlery:'20',sweet:true,weight:'2750'}],
        detImages:['tjl51_1.jpg','tjl51_3.jpg'],
        p:'纽约的秋天，是迷人的。不仅是她的繁华，还有中央公园的娴静。惬意踩着遍地的红叶，贪恋着午后阳光的温暖，这种香甜，是我俩之间的联系。',
        aboutFood:[{a1:'栗子蓉',b1:'英雄',c1:'瑞士',
            a2:'黑巧克力',b2:'嘉利宝/贝克拉',c2:'比利时',
            a3:'淡奶油',b3:'铁塔/安佳',c3:'进口',
            a4:'幼砂糖',b4:'雪花',c4:'韩国',
            a5:'核桃仁',b5:'三路',c5:'美国'}],
        aboutEat:'慕斯口味'
    },
    {
        id: 52,
        name: '阿尔蒙麦香蛋糕',
		enName:"Almond Oatmeal Aroma", 
        price: '198.00',
        isRecommend: false,
        isNews: false,
        isBlast: false,
        isHot: false,
        isSign: false,
        isSale: false,
        isPrompt: false,
        isLimit: false,
        isStand: false,
        images:['tjl52_1.jpg','tjl52_2.jpg'],
        norms:[
            {offer:'2-4',price:'198.00',content:'13*13',cutlery:'5',sweet:true,weight:'400'},
            {offer:'5-8',price:'298.00',content:'17*17',cutlery:'10',sweet:true,weight:'690'},
            {offer:'10-12',price:'458.00',content:'22*22',cutlery:'15',sweet:true,weight:'1100'},
            {offer:'15-20',price:'756.00',content:'31*31',cutlery:'20',sweet:true,weight:'2100'}
        ],
        detImages:['tjl52_3.jpg','tjl52_4.jpg'],
        p:'曾怀念童年时那夕阳西下的时刻，阳光透过田园小木屋的窗格，洒在梵高画里一般的麦垛上。闻着厨房里透出的丝丝缕缕的香味，那是祖母烤巴旦木的味道。而远离了田园的我，从此眷恋着在麦堆上熟睡的乐趣。',
        aboutFood:[{a1:'淡奶油',b1:'铁塔/安佳',c1:'进口',
            a2:'黄油',b2:'铁塔/安佳',c2:'进口'}],
        aboutEat:'慕斯口味'
    },
    {
        id: 53,
        name: '阿尔蒙洛克蛋糕',
		enName:"Almond Rocks Cake", 
        price: '198.00',
        isRecommend: false,
        isNews: false,
        isBlast: false,
        isHot: false,
        isSign: false,
        isSale: false,
        isPrompt: false,
        isLimit: false,
        isStand: false,
        images:['tjl53_1.jpg','tjl53_2.jpg'],
        norms:[{offer:'2-4',price:'198.00',content:'13*13',cutlery:'5',sweet:true,weight:'370'},
            {offer:'5-8',price:'298.00',content:'17*17',cutlery:'10',sweet:true,weight:'660'},
            {offer:'10-12',price:'458.00',content:'22*22',cutlery:'15',sweet:true,weight:'1050'},
            {offer:'15-20',price:'756.00',content:'31*31',cutlery:'20',sweet:true,weight:'2050'}],
        detImages:['tjl53_3.jpg','tjl53_4.jpg'],
        p:'机场永远充满笑与泪，相同的剧目，每天都在上演。离别、重聚、离别，我确信，离开，是为了回来。我相信，回来的人，是懂得拥抱幸福的人。',
        aboutFood:[{a1:'淡奶油',b1:'铁塔/安佳',c1:'进口',
            a2:'黄油',b2:'铁塔/安佳',c2:'进口',
            a3:'幼砂糖',b3:'雪花',c3:'韩国',
            a4:'可可粉',b4:'马天尼',c4:'荷兰'}],
        aboutEat:'慕斯口味'
    },
    {
        id: 54,
        name: '西雅图之夜',
		enName:"Seattle Dream", 
        price: '218.00',
        isRecommend: false,
        isNews: false,
        isBlast: false,
        isHot: false,
        isSign: false,
        isSale: false,
        isPrompt: false,
        isLimit: false,
        isStand: false,
        images:['tjl54_1.jpg'],
        norms:[{offer:'4-6',price:'218.00',content:'17*17',cutlery:'10',sweet:true,weight:'727'}],
        detImages:['tjl54_2.jpg','tjl54_3.jpg'],
        p:'梦与幻想在纯雪中邂逅，心动所带来丰硕的果实，赋予人们酸甜回甘的人生滋味。有多少人迷恋西雅图之夜并且相信奇迹，而这些赋予真心的人都值得收获幸福。',
        aboutFood:[{a1:'无盐黄油',b1:'Anchor',c1:'Anchor',
            a2:'白砂糖',b2:'Foodream',c2:'韩国',
            a3:'牛奶',b3:'Del Leche',c3:'法国'}],
        aboutEat:'鲜果口味'
    }
];



